### ISSUE TITLE
Update API endpoints to follow "convention"

### ISSUE THREAD

**Issue by dreadster3** [Ghergutftw/Vetclinic#1]
# Example
Host: http://localhost:1010/service

## Get All
GET to http://localhost:1010/service

## Get by Attribute
GET to http://localhost:1010/service?attribute=example

## Get by Id
GET to http://localhost:1010/service/{id}

## Create new
POST to http://localhost:1010/service

## Update existing
PUT to http://localhost:1010/service/{id}

## Patch existing
PATCH to http://localhost:1010/service/{id}

## Delete existing
DELETE to http://localhost:1010/service/{id}

# References
- https://restfulapi.net/resource-naming/

**Comment by Ghergutftw** [comment]
https://github.com/Ghergutftw/Vetclinic/commit/ca1756b851ac5af8fe0a8deb31f650d3f928b61f
